workflows:
  ios-adhoc:
    name: iOS AdHoc

    environment:
      flutter: 3.41.4

      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.equivalencias.crisfiit

    scripts:
      - flutter pub get
      - xcode-project use-profiles
      - flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa


  ios-appstore:
    name: iOS App Store

    environment:
      flutter: 3.41.4

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.equivalencias.crisfiit

    scripts:
      - flutter pub get
      - xcode-project use-profiles
      - flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration