workflows:
  ios-adhoc:
    name: iOS AdHoc
    max_build_duration: 60

    environment:
      flutter: stable

      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.equivalencias.crisfiit

    scripts:
      - flutter pub get
      - flutter build ipa --release --export-method ad-hoc

    artifacts:
      - build/ios/ipa/*.ipa

  ios-appstore:
    name: iOS App Store
    max_build_duration: 60

    environment:
      flutter: stable

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.equivalencias.crisfiit

    scripts:
      - flutter pub get
      - flutter build ipa --release --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa