// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISiv5ptEBgSpVXG1eXio4vBJ3NZZKNC4',
    appId: '1:776056212786:web:2ecf7b9721d12919b25b2b',
    messagingSenderId: '776056212786',
    projectId: 'crisfiit',
    authDomain: 'crisfiit.firebaseapp.com',
    storageBucket: 'crisfiit.firebasestorage.app',
    measurementId: 'G-W16PQ0FJK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAug6yZ70HUyUBlaBTv5AzCmcCDg6DuWf8',
    appId: '1:776056212786:android:a44507e1c94ba616b25b2b',
    messagingSenderId: '776056212786',
    projectId: 'crisfiit',
    storageBucket: 'crisfiit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxhLqo8KIeYn8wMTHR_-mac4_STgTZqss',
    appId: '1:776056212786:ios:aa4249a07899348db25b2b',
    messagingSenderId: '776056212786',
    projectId: 'crisfiit',
    storageBucket: 'crisfiit.firebasestorage.app',
    iosBundleId: 'com.equivalencias.crisfiit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCISiv5ptEBgSpVXG1eXio4vBJ3NZZKNC4',
    appId: '1:776056212786:web:e60dbec9571234e3b25b2b',
    messagingSenderId: '776056212786',
    projectId: 'crisfiit',
    authDomain: 'crisfiit.firebaseapp.com',
    storageBucket: 'crisfiit.firebasestorage.app',
    measurementId: 'G-H2S7F6HFFX',
  );
}
